# Generated by Django 4.2.5 on 2023-10-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='name', max_length=128),
            preserve_default=False,
        ),
    ]
