# Generated by Django 4.2.5 on 2023-10-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='name', unique=True),
            preserve_default=False,
        ),
    ]
