# Generated by Django 4.2.6 on 2023-10-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_brand_profile_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=4096, null=True),
        ),
    ]
