# Generated by Django 4.2.6 on 2023-10-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='img/1_UFg0L92.jpg', upload_to='img/category'),
            preserve_default=False,
        ),
    ]
