# Generated by Django 4.2.6 on 2023-10-23 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Address',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
